docker:
  image: yegor256/java8
assets:
  settings.xml: zerocracy/home#assets/zerocracy/settings.xml
  pubring.gpg: zerocracy/home#assets/pubring.gpg
  secring.gpg: zerocracy/home#assets/secring.gpg
  s3cfg: zerocracy/home#assets/s3cfg
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
  JAVA_OPTS: -XX:MaxPermSize=256m -Xmx1g
install: |
  sudo gem install --no-rdoc --no-ri pdd
  sudo gem install --no-rdoc --no-ri est
architect:
- yegor256
merge:
  script: |
    mvn clean install -Pzc-jstk -Pqulice --errors --settings ../settings.xml
    mvn clean site -Psite --errors --settings ../settings.xml
    mvn clean
    pdd --source=$(pwd) --verbose --file=/dev/null
  commanders:
  - yegor256
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pzc-jstk -Psonatype --errors --settings ../settings.xml
  commanders:
  - yegor256
